name: CI Build and Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Tools
        run: |
          sudo apt-get update
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 20
          sudo apt-get install -y ninja-build clang-tidy clang-format-20 libgtest-dev

      - name: Configure CMake
        run: cmake -S . -B build -G Ninja -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DBUILD_TESTS=ON

      - name: Run Clang-Tidy
        run: clang-tidy -p build/ src/*.c --warnings-as-errors='*'
      
      - name: Check Formatting
        run: |
          find src include tests -name '*.[ch]' -o -name '*.c' | xargs clang-format-20 --dry-run --Werror -style=file

      - name: Build
        run: cmake --build build

      - name: Run Tests
        run: ./bin/unit_tests
